---

- name: wait for remote ports
  wait_for:
    host: "{{ item.ip }}"
    port: >-
      {{ item.winrm_port
          if (item.winrm_port | int) > 0
        else
          item.ssh_port
      }}
    timeout: 360 # seconds
  become: false
  delegate_to: 127.0.0.1
  with_items: "{{ libvirt_wait_hosts }}"

# wait_for might not be enough for a successful SSH login, probably due to
# https://stackoverflow.com/questions/30576778/ansible-wait-for-for-connecting-machine-to-actually-login#comment60208811_30576778
- name: check ssh login
  setup:
    retries: 12
    delay:  5
  changed_when: false
  become: false
  delegate_to: "{{ item }}"
  with_items: "{{ libvirt_wait_hosts }}"
